ERROR - 2023-02-09 10:40:29 --> Error connecting to the database: mysqli_sql_exception: Access denied for user ''@'localhost' (using password: NO) in C:\xampp\htdocs\ci1\system\Database\MySQLi\Connection.php:174
Stack trace:
#0 C:\xampp\htdocs\ci1\system\Database\MySQLi\Connection.php(174): mysqli->real_connect('localhost', '', '', 'codeign', 3306, '', 0)
#1 C:\xampp\htdocs\ci1\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\xampp\htdocs\ci1\system\Database\BaseConnection.php(573): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\xampp\htdocs\ci1\app\Controllers\Users.php(10): CodeIgniter\Database\BaseConnection->query('select * from c...')
#4 C:\xampp\htdocs\ci1\system\CodeIgniter.php(934): App\Controllers\Users->index()
#5 C:\xampp\htdocs\ci1\system\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Users))
#6 C:\xampp\htdocs\ci1\system\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#7 C:\xampp\htdocs\ci1\index.php(67): CodeIgniter\CodeIgniter->run()
#8 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user ''@'localhost' (using password: NO) in C:\xampp\htdocs\ci1\system\Database\MySQLi\Connection.php:218
Stack trace:
#0 C:\xampp\htdocs\ci1\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\xampp\htdocs\ci1\system\Database\BaseConnection.php(573): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\xampp\htdocs\ci1\app\Controllers\Users.php(10): CodeIgniter\Database\BaseConnection->query('select * from c...')
#3 C:\xampp\htdocs\ci1\system\CodeIgniter.php(934): App\Controllers\Users->index()
#4 C:\xampp\htdocs\ci1\system\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Users))
#5 C:\xampp\htdocs\ci1\system\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#6 C:\xampp\htdocs\ci1\index.php(67): CodeIgniter\CodeIgniter->run()
#7 {main}
CRITICAL - 2023-02-09 10:40:29 --> Unable to connect to the database.
Main connection [MySQLi]: Access denied for user ''@'localhost' (using password: NO)
in SYSTEMPATH\Database\BaseConnection.php on line 427.
 1 SYSTEMPATH\Database\BaseConnection.php(573): CodeIgniter\Database\BaseConnection->initialize()
 2 APPPATH\Controllers\Users.php(10): CodeIgniter\Database\BaseConnection->query('select * from course_table')
 3 SYSTEMPATH\CodeIgniter.php(934): App\Controllers\Users->index()
 4 SYSTEMPATH\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Users))
 5 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 6 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
ERROR - 2023-02-09 10:41:30 --> Error connecting to the database: mysqli_sql_exception: Access denied for user ''@'localhost' (using password: NO) in C:\xampp\htdocs\ci1\system\Database\MySQLi\Connection.php:174
Stack trace:
#0 C:\xampp\htdocs\ci1\system\Database\MySQLi\Connection.php(174): mysqli->real_connect('localhost', '', '', 'codeign', 3306, '', 0)
#1 C:\xampp\htdocs\ci1\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\xampp\htdocs\ci1\system\Database\BaseConnection.php(573): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\xampp\htdocs\ci1\app\Controllers\Users.php(10): CodeIgniter\Database\BaseConnection->query('select * from c...')
#4 C:\xampp\htdocs\ci1\system\CodeIgniter.php(934): App\Controllers\Users->index()
#5 C:\xampp\htdocs\ci1\system\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Users))
#6 C:\xampp\htdocs\ci1\system\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#7 C:\xampp\htdocs\ci1\index.php(67): CodeIgniter\CodeIgniter->run()
#8 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user ''@'localhost' (using password: NO) in C:\xampp\htdocs\ci1\system\Database\MySQLi\Connection.php:218
Stack trace:
#0 C:\xampp\htdocs\ci1\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\xampp\htdocs\ci1\system\Database\BaseConnection.php(573): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\xampp\htdocs\ci1\app\Controllers\Users.php(10): CodeIgniter\Database\BaseConnection->query('select * from c...')
#3 C:\xampp\htdocs\ci1\system\CodeIgniter.php(934): App\Controllers\Users->index()
#4 C:\xampp\htdocs\ci1\system\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Users))
#5 C:\xampp\htdocs\ci1\system\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#6 C:\xampp\htdocs\ci1\index.php(67): CodeIgniter\CodeIgniter->run()
#7 {main}
CRITICAL - 2023-02-09 10:41:30 --> Unable to connect to the database.
Main connection [MySQLi]: Access denied for user ''@'localhost' (using password: NO)
in SYSTEMPATH\Database\BaseConnection.php on line 427.
 1 SYSTEMPATH\Database\BaseConnection.php(573): CodeIgniter\Database\BaseConnection->initialize()
 2 APPPATH\Controllers\Users.php(10): CodeIgniter\Database\BaseConnection->query('select * from course_table')
 3 SYSTEMPATH\CodeIgniter.php(934): App\Controllers\Users->index()
 4 SYSTEMPATH\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Users))
 5 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 6 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
ERROR - 2023-02-09 10:41:32 --> Error connecting to the database: mysqli_sql_exception: Access denied for user ''@'localhost' (using password: NO) in C:\xampp\htdocs\ci1\system\Database\MySQLi\Connection.php:174
Stack trace:
#0 C:\xampp\htdocs\ci1\system\Database\MySQLi\Connection.php(174): mysqli->real_connect('localhost', '', '', 'codeign', 3306, '', 0)
#1 C:\xampp\htdocs\ci1\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\xampp\htdocs\ci1\system\Database\BaseConnection.php(573): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\xampp\htdocs\ci1\app\Controllers\Users.php(10): CodeIgniter\Database\BaseConnection->query('select * from c...')
#4 C:\xampp\htdocs\ci1\system\CodeIgniter.php(934): App\Controllers\Users->index()
#5 C:\xampp\htdocs\ci1\system\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Users))
#6 C:\xampp\htdocs\ci1\system\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#7 C:\xampp\htdocs\ci1\index.php(67): CodeIgniter\CodeIgniter->run()
#8 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user ''@'localhost' (using password: NO) in C:\xampp\htdocs\ci1\system\Database\MySQLi\Connection.php:218
Stack trace:
#0 C:\xampp\htdocs\ci1\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\xampp\htdocs\ci1\system\Database\BaseConnection.php(573): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\xampp\htdocs\ci1\app\Controllers\Users.php(10): CodeIgniter\Database\BaseConnection->query('select * from c...')
#3 C:\xampp\htdocs\ci1\system\CodeIgniter.php(934): App\Controllers\Users->index()
#4 C:\xampp\htdocs\ci1\system\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Users))
#5 C:\xampp\htdocs\ci1\system\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#6 C:\xampp\htdocs\ci1\index.php(67): CodeIgniter\CodeIgniter->run()
#7 {main}
CRITICAL - 2023-02-09 10:41:32 --> Unable to connect to the database.
Main connection [MySQLi]: Access denied for user ''@'localhost' (using password: NO)
in SYSTEMPATH\Database\BaseConnection.php on line 427.
 1 SYSTEMPATH\Database\BaseConnection.php(573): CodeIgniter\Database\BaseConnection->initialize()
 2 APPPATH\Controllers\Users.php(10): CodeIgniter\Database\BaseConnection->query('select * from course_table')
 3 SYSTEMPATH\CodeIgniter.php(934): App\Controllers\Users->index()
 4 SYSTEMPATH\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Users))
 5 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 6 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
ERROR - 2023-02-09 10:43:28 --> Error connecting to the database: mysqli_sql_exception: No connection could be made because the target machine actively refused it.
 in C:\xampp\htdocs\ci1\system\Database\MySQLi\Connection.php:174
Stack trace:
#0 C:\xampp\htdocs\ci1\system\Database\MySQLi\Connection.php(174): mysqli->real_connect('localhost:3308', '', '', 'codeign', 3306, '', 0)
#1 C:\xampp\htdocs\ci1\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\xampp\htdocs\ci1\system\Database\BaseConnection.php(573): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\xampp\htdocs\ci1\app\Controllers\Users.php(10): CodeIgniter\Database\BaseConnection->query('select * from c...')
#4 C:\xampp\htdocs\ci1\system\CodeIgniter.php(934): App\Controllers\Users->index()
#5 C:\xampp\htdocs\ci1\system\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Users))
#6 C:\xampp\htdocs\ci1\system\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#7 C:\xampp\htdocs\ci1\index.php(67): CodeIgniter\CodeIgniter->run()
#8 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: No connection could be made because the target machine actively refused it.
 in C:\xampp\htdocs\ci1\system\Database\MySQLi\Connection.php:218
Stack trace:
#0 C:\xampp\htdocs\ci1\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\xampp\htdocs\ci1\system\Database\BaseConnection.php(573): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\xampp\htdocs\ci1\app\Controllers\Users.php(10): CodeIgniter\Database\BaseConnection->query('select * from c...')
#3 C:\xampp\htdocs\ci1\system\CodeIgniter.php(934): App\Controllers\Users->index()
#4 C:\xampp\htdocs\ci1\system\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Users))
#5 C:\xampp\htdocs\ci1\system\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#6 C:\xampp\htdocs\ci1\index.php(67): CodeIgniter\CodeIgniter->run()
#7 {main}
CRITICAL - 2023-02-09 10:43:28 --> Unable to connect to the database.
Main connection [MySQLi]: No connection could be made because the target machine actively refused it.

in SYSTEMPATH\Database\BaseConnection.php on line 427.
 1 SYSTEMPATH\Database\BaseConnection.php(573): CodeIgniter\Database\BaseConnection->initialize()
 2 APPPATH\Controllers\Users.php(10): CodeIgniter\Database\BaseConnection->query('select * from course_table')
 3 SYSTEMPATH\CodeIgniter.php(934): App\Controllers\Users->index()
 4 SYSTEMPATH\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Users))
 5 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 6 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
ERROR - 2023-02-09 10:44:40 --> Error connecting to the database: mysqli_sql_exception: Access denied for user ''@'localhost' (using password: NO) in C:\xampp\htdocs\ci1\system\Database\MySQLi\Connection.php:174
Stack trace:
#0 C:\xampp\htdocs\ci1\system\Database\MySQLi\Connection.php(174): mysqli->real_connect('localhost:3306', '', '', 'codeign', 3306, '', 0)
#1 C:\xampp\htdocs\ci1\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\xampp\htdocs\ci1\system\Database\BaseConnection.php(573): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\xampp\htdocs\ci1\app\Controllers\Users.php(10): CodeIgniter\Database\BaseConnection->query('select * from c...')
#4 C:\xampp\htdocs\ci1\system\CodeIgniter.php(934): App\Controllers\Users->index()
#5 C:\xampp\htdocs\ci1\system\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Users))
#6 C:\xampp\htdocs\ci1\system\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#7 C:\xampp\htdocs\ci1\index.php(67): CodeIgniter\CodeIgniter->run()
#8 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user ''@'localhost' (using password: NO) in C:\xampp\htdocs\ci1\system\Database\MySQLi\Connection.php:218
Stack trace:
#0 C:\xampp\htdocs\ci1\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\xampp\htdocs\ci1\system\Database\BaseConnection.php(573): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\xampp\htdocs\ci1\app\Controllers\Users.php(10): CodeIgniter\Database\BaseConnection->query('select * from c...')
#3 C:\xampp\htdocs\ci1\system\CodeIgniter.php(934): App\Controllers\Users->index()
#4 C:\xampp\htdocs\ci1\system\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Users))
#5 C:\xampp\htdocs\ci1\system\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#6 C:\xampp\htdocs\ci1\index.php(67): CodeIgniter\CodeIgniter->run()
#7 {main}
CRITICAL - 2023-02-09 10:44:40 --> Unable to connect to the database.
Main connection [MySQLi]: Access denied for user ''@'localhost' (using password: NO)
in SYSTEMPATH\Database\BaseConnection.php on line 427.
 1 SYSTEMPATH\Database\BaseConnection.php(573): CodeIgniter\Database\BaseConnection->initialize()
 2 APPPATH\Controllers\Users.php(10): CodeIgniter\Database\BaseConnection->query('select * from course_table')
 3 SYSTEMPATH\CodeIgniter.php(934): App\Controllers\Users->index()
 4 SYSTEMPATH\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Users))
 5 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 6 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
ERROR - 2023-02-09 10:44:41 --> Error connecting to the database: mysqli_sql_exception: Access denied for user ''@'localhost' (using password: NO) in C:\xampp\htdocs\ci1\system\Database\MySQLi\Connection.php:174
Stack trace:
#0 C:\xampp\htdocs\ci1\system\Database\MySQLi\Connection.php(174): mysqli->real_connect('localhost:3306', '', '', 'codeign', 3306, '', 0)
#1 C:\xampp\htdocs\ci1\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\xampp\htdocs\ci1\system\Database\BaseConnection.php(573): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\xampp\htdocs\ci1\app\Controllers\Users.php(10): CodeIgniter\Database\BaseConnection->query('select * from c...')
#4 C:\xampp\htdocs\ci1\system\CodeIgniter.php(934): App\Controllers\Users->index()
#5 C:\xampp\htdocs\ci1\system\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Users))
#6 C:\xampp\htdocs\ci1\system\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#7 C:\xampp\htdocs\ci1\index.php(67): CodeIgniter\CodeIgniter->run()
#8 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user ''@'localhost' (using password: NO) in C:\xampp\htdocs\ci1\system\Database\MySQLi\Connection.php:218
Stack trace:
#0 C:\xampp\htdocs\ci1\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\xampp\htdocs\ci1\system\Database\BaseConnection.php(573): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\xampp\htdocs\ci1\app\Controllers\Users.php(10): CodeIgniter\Database\BaseConnection->query('select * from c...')
#3 C:\xampp\htdocs\ci1\system\CodeIgniter.php(934): App\Controllers\Users->index()
#4 C:\xampp\htdocs\ci1\system\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Users))
#5 C:\xampp\htdocs\ci1\system\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#6 C:\xampp\htdocs\ci1\index.php(67): CodeIgniter\CodeIgniter->run()
#7 {main}
CRITICAL - 2023-02-09 10:44:41 --> Unable to connect to the database.
Main connection [MySQLi]: Access denied for user ''@'localhost' (using password: NO)
in SYSTEMPATH\Database\BaseConnection.php on line 427.
 1 SYSTEMPATH\Database\BaseConnection.php(573): CodeIgniter\Database\BaseConnection->initialize()
 2 APPPATH\Controllers\Users.php(10): CodeIgniter\Database\BaseConnection->query('select * from course_table')
 3 SYSTEMPATH\CodeIgniter.php(934): App\Controllers\Users->index()
 4 SYSTEMPATH\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Users))
 5 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 6 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
ERROR - 2023-02-09 10:44:49 --> Error connecting to the database: mysqli_sql_exception: No connection could be made because the target machine actively refused it.
 in C:\xampp\htdocs\ci1\system\Database\MySQLi\Connection.php:174
Stack trace:
#0 C:\xampp\htdocs\ci1\system\Database\MySQLi\Connection.php(174): mysqli->real_connect('localhost:3308', '', '', 'codeign', 3306, '', 0)
#1 C:\xampp\htdocs\ci1\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\xampp\htdocs\ci1\system\Database\BaseConnection.php(573): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\xampp\htdocs\ci1\app\Controllers\Users.php(10): CodeIgniter\Database\BaseConnection->query('select * from c...')
#4 C:\xampp\htdocs\ci1\system\CodeIgniter.php(934): App\Controllers\Users->index()
#5 C:\xampp\htdocs\ci1\system\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Users))
#6 C:\xampp\htdocs\ci1\system\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#7 C:\xampp\htdocs\ci1\index.php(67): CodeIgniter\CodeIgniter->run()
#8 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: No connection could be made because the target machine actively refused it.
 in C:\xampp\htdocs\ci1\system\Database\MySQLi\Connection.php:218
Stack trace:
#0 C:\xampp\htdocs\ci1\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\xampp\htdocs\ci1\system\Database\BaseConnection.php(573): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\xampp\htdocs\ci1\app\Controllers\Users.php(10): CodeIgniter\Database\BaseConnection->query('select * from c...')
#3 C:\xampp\htdocs\ci1\system\CodeIgniter.php(934): App\Controllers\Users->index()
#4 C:\xampp\htdocs\ci1\system\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Users))
#5 C:\xampp\htdocs\ci1\system\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#6 C:\xampp\htdocs\ci1\index.php(67): CodeIgniter\CodeIgniter->run()
#7 {main}
CRITICAL - 2023-02-09 10:44:49 --> Unable to connect to the database.
Main connection [MySQLi]: No connection could be made because the target machine actively refused it.

in SYSTEMPATH\Database\BaseConnection.php on line 427.
 1 SYSTEMPATH\Database\BaseConnection.php(573): CodeIgniter\Database\BaseConnection->initialize()
 2 APPPATH\Controllers\Users.php(10): CodeIgniter\Database\BaseConnection->query('select * from course_table')
 3 SYSTEMPATH\CodeIgniter.php(934): App\Controllers\Users->index()
 4 SYSTEMPATH\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Users))
 5 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 6 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
ERROR - 2023-02-09 10:45:15 --> Error connecting to the database: mysqli_sql_exception: No connection could be made because the target machine actively refused it.
 in C:\xampp\htdocs\ci1\system\Database\MySQLi\Connection.php:174
Stack trace:
#0 C:\xampp\htdocs\ci1\system\Database\MySQLi\Connection.php(174): mysqli->real_connect('localhost:3308', '', '', 'codeign', 3306, '', 0)
#1 C:\xampp\htdocs\ci1\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\xampp\htdocs\ci1\system\Database\BaseConnection.php(573): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\xampp\htdocs\ci1\app\Controllers\Users.php(10): CodeIgniter\Database\BaseConnection->query('select * from c...')
#4 C:\xampp\htdocs\ci1\system\CodeIgniter.php(934): App\Controllers\Users->index()
#5 C:\xampp\htdocs\ci1\system\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Users))
#6 C:\xampp\htdocs\ci1\system\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#7 C:\xampp\htdocs\ci1\index.php(67): CodeIgniter\CodeIgniter->run()
#8 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: No connection could be made because the target machine actively refused it.
 in C:\xampp\htdocs\ci1\system\Database\MySQLi\Connection.php:218
Stack trace:
#0 C:\xampp\htdocs\ci1\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\xampp\htdocs\ci1\system\Database\BaseConnection.php(573): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\xampp\htdocs\ci1\app\Controllers\Users.php(10): CodeIgniter\Database\BaseConnection->query('select * from c...')
#3 C:\xampp\htdocs\ci1\system\CodeIgniter.php(934): App\Controllers\Users->index()
#4 C:\xampp\htdocs\ci1\system\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Users))
#5 C:\xampp\htdocs\ci1\system\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#6 C:\xampp\htdocs\ci1\index.php(67): CodeIgniter\CodeIgniter->run()
#7 {main}
CRITICAL - 2023-02-09 10:45:15 --> Unable to connect to the database.
Main connection [MySQLi]: No connection could be made because the target machine actively refused it.

in SYSTEMPATH\Database\BaseConnection.php on line 427.
 1 SYSTEMPATH\Database\BaseConnection.php(573): CodeIgniter\Database\BaseConnection->initialize()
 2 APPPATH\Controllers\Users.php(10): CodeIgniter\Database\BaseConnection->query('select * from course_table')
 3 SYSTEMPATH\CodeIgniter.php(934): App\Controllers\Users->index()
 4 SYSTEMPATH\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Users))
 5 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 6 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
ERROR - 2023-02-09 10:45:25 --> Error connecting to the database: mysqli_sql_exception: No connection could be made because the target machine actively refused it.
 in C:\xampp\htdocs\ci1\system\Database\MySQLi\Connection.php:174
Stack trace:
#0 C:\xampp\htdocs\ci1\system\Database\MySQLi\Connection.php(174): mysqli->real_connect('localhost:3308', '', '', 'codeign', 3306, '', 0)
#1 C:\xampp\htdocs\ci1\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\xampp\htdocs\ci1\system\Database\BaseConnection.php(573): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\xampp\htdocs\ci1\app\Controllers\Users.php(10): CodeIgniter\Database\BaseConnection->query('select * from c...')
#4 C:\xampp\htdocs\ci1\system\CodeIgniter.php(934): App\Controllers\Users->index()
#5 C:\xampp\htdocs\ci1\system\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Users))
#6 C:\xampp\htdocs\ci1\system\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#7 C:\xampp\htdocs\ci1\index.php(67): CodeIgniter\CodeIgniter->run()
#8 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: No connection could be made because the target machine actively refused it.
 in C:\xampp\htdocs\ci1\system\Database\MySQLi\Connection.php:218
Stack trace:
#0 C:\xampp\htdocs\ci1\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\xampp\htdocs\ci1\system\Database\BaseConnection.php(573): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\xampp\htdocs\ci1\app\Controllers\Users.php(10): CodeIgniter\Database\BaseConnection->query('select * from c...')
#3 C:\xampp\htdocs\ci1\system\CodeIgniter.php(934): App\Controllers\Users->index()
#4 C:\xampp\htdocs\ci1\system\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Users))
#5 C:\xampp\htdocs\ci1\system\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#6 C:\xampp\htdocs\ci1\index.php(67): CodeIgniter\CodeIgniter->run()
#7 {main}
CRITICAL - 2023-02-09 10:45:25 --> Unable to connect to the database.
Main connection [MySQLi]: No connection could be made because the target machine actively refused it.

in SYSTEMPATH\Database\BaseConnection.php on line 427.
 1 SYSTEMPATH\Database\BaseConnection.php(573): CodeIgniter\Database\BaseConnection->initialize()
 2 APPPATH\Controllers\Users.php(10): CodeIgniter\Database\BaseConnection->query('select * from course_table')
 3 SYSTEMPATH\CodeIgniter.php(934): App\Controllers\Users->index()
 4 SYSTEMPATH\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Users))
 5 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 6 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
ERROR - 2023-02-09 10:45:46 --> Error connecting to the database: mysqli_sql_exception: No connection could be made because the target machine actively refused it.
 in C:\xampp\htdocs\ci1\system\Database\MySQLi\Connection.php:174
Stack trace:
#0 C:\xampp\htdocs\ci1\system\Database\MySQLi\Connection.php(174): mysqli->real_connect('localhost:3308', '', '', 'codeign', 3306, '', 0)
#1 C:\xampp\htdocs\ci1\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\xampp\htdocs\ci1\system\Database\BaseConnection.php(573): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\xampp\htdocs\ci1\app\Controllers\Users.php(11): CodeIgniter\Database\BaseConnection->query('select * from c...')
#4 C:\xampp\htdocs\ci1\system\CodeIgniter.php(934): App\Controllers\Users->index()
#5 C:\xampp\htdocs\ci1\system\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Users))
#6 C:\xampp\htdocs\ci1\system\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#7 C:\xampp\htdocs\ci1\index.php(67): CodeIgniter\CodeIgniter->run()
#8 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: No connection could be made because the target machine actively refused it.
 in C:\xampp\htdocs\ci1\system\Database\MySQLi\Connection.php:218
Stack trace:
#0 C:\xampp\htdocs\ci1\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\xampp\htdocs\ci1\system\Database\BaseConnection.php(573): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\xampp\htdocs\ci1\app\Controllers\Users.php(11): CodeIgniter\Database\BaseConnection->query('select * from c...')
#3 C:\xampp\htdocs\ci1\system\CodeIgniter.php(934): App\Controllers\Users->index()
#4 C:\xampp\htdocs\ci1\system\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Users))
#5 C:\xampp\htdocs\ci1\system\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#6 C:\xampp\htdocs\ci1\index.php(67): CodeIgniter\CodeIgniter->run()
#7 {main}
CRITICAL - 2023-02-09 10:45:46 --> Unable to connect to the database.
Main connection [MySQLi]: No connection could be made because the target machine actively refused it.

in SYSTEMPATH\Database\BaseConnection.php on line 427.
 1 SYSTEMPATH\Database\BaseConnection.php(573): CodeIgniter\Database\BaseConnection->initialize()
 2 APPPATH\Controllers\Users.php(11): CodeIgniter\Database\BaseConnection->query('select * from course_table')
 3 SYSTEMPATH\CodeIgniter.php(934): App\Controllers\Users->index()
 4 SYSTEMPATH\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Users))
 5 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 6 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
ERROR - 2023-02-09 11:03:54 --> Error connecting to the database: mysqli_sql_exception: Unknown database 'ci4' in C:\xampp\htdocs\ci1\system\Database\MySQLi\Connection.php:174
Stack trace:
#0 C:\xampp\htdocs\ci1\system\Database\MySQLi\Connection.php(174): mysqli->real_connect('localhost', 'root', '', 'ci4', 3306, '', 0)
#1 C:\xampp\htdocs\ci1\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\xampp\htdocs\ci1\system\Database\BaseConnection.php(573): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\xampp\htdocs\ci1\app\Controllers\Users.php(10): CodeIgniter\Database\BaseConnection->query('select * from c...')
#4 C:\xampp\htdocs\ci1\system\CodeIgniter.php(934): App\Controllers\Users->index()
#5 C:\xampp\htdocs\ci1\system\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Users))
#6 C:\xampp\htdocs\ci1\system\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#7 C:\xampp\htdocs\ci1\index.php(67): CodeIgniter\CodeIgniter->run()
#8 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Unknown database 'ci4' in C:\xampp\htdocs\ci1\system\Database\MySQLi\Connection.php:218
Stack trace:
#0 C:\xampp\htdocs\ci1\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\xampp\htdocs\ci1\system\Database\BaseConnection.php(573): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\xampp\htdocs\ci1\app\Controllers\Users.php(10): CodeIgniter\Database\BaseConnection->query('select * from c...')
#3 C:\xampp\htdocs\ci1\system\CodeIgniter.php(934): App\Controllers\Users->index()
#4 C:\xampp\htdocs\ci1\system\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Users))
#5 C:\xampp\htdocs\ci1\system\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#6 C:\xampp\htdocs\ci1\index.php(67): CodeIgniter\CodeIgniter->run()
#7 {main}
CRITICAL - 2023-02-09 11:03:54 --> Unable to connect to the database.
Main connection [MySQLi]: Unknown database 'ci4'
in SYSTEMPATH\Database\BaseConnection.php on line 427.
 1 SYSTEMPATH\Database\BaseConnection.php(573): CodeIgniter\Database\BaseConnection->initialize()
 2 APPPATH\Controllers\Users.php(10): CodeIgniter\Database\BaseConnection->query('select * from course_table')
 3 SYSTEMPATH\CodeIgniter.php(934): App\Controllers\Users->index()
 4 SYSTEMPATH\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Users))
 5 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 6 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
CRITICAL - 2023-02-09 11:41:12 --> Argument 1 passed to CodeIgniter\View\Table::_prepArgs() must be of the type array, object given, called in C:\xampp\htdocs\ci1\system\View\Table.php on line 435
in SYSTEMPATH\View\Table.php on line 222.
 1 SYSTEMPATH\View\Table.php(435): CodeIgniter\View\Table->_prepArgs(Object(stdClass))
 2 SYSTEMPATH\View\Table.php(269): CodeIgniter\View\Table->_setFromArray([...])
 3 APPPATH\Controllers\Users.php(13): CodeIgniter\View\Table->generate([...])
 4 SYSTEMPATH\CodeIgniter.php(934): App\Controllers\Users->index()
 5 SYSTEMPATH\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Users))
 6 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 7 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
CRITICAL - 2023-02-09 12:17:45 --> "required," is not a valid rule.
in SYSTEMPATH\Validation\Validation.php on line 320.
 1 SYSTEMPATH\Validation\Validation.php(320): CodeIgniter\Validation\Exceptions\ValidationException::forRuleNotFound('required,')
 2 SYSTEMPATH\Validation\Validation.php(170): CodeIgniter\Validation\Validation->processRules('name', 'name', null, [...], [...])
 3 SYSTEMPATH\Controller.php(140): CodeIgniter\Validation\Validation->run()
 4 APPPATH\Controllers\Welcome.php(25): CodeIgniter\Controller->validate([...])
 5 SYSTEMPATH\CodeIgniter.php(934): App\Controllers\Welcome->index()
 6 SYSTEMPATH\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Welcome))
 7 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 8 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
CRITICAL - 2023-02-09 12:18:13 --> "required," is not a valid rule.
in SYSTEMPATH\Validation\Validation.php on line 320.
 1 SYSTEMPATH\Validation\Validation.php(320): CodeIgniter\Validation\Exceptions\ValidationException::forRuleNotFound('required,')
 2 SYSTEMPATH\Validation\Validation.php(170): CodeIgniter\Validation\Validation->processRules('name', 'name', null, [...], [...])
 3 SYSTEMPATH\Controller.php(140): CodeIgniter\Validation\Validation->run()
 4 APPPATH\Controllers\Welcome.php(25): CodeIgniter\Controller->validate([...])
 5 SYSTEMPATH\CodeIgniter.php(934): App\Controllers\Welcome->index()
 6 SYSTEMPATH\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Welcome))
 7 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 8 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
CRITICAL - 2023-02-09 12:18:15 --> "required," is not a valid rule.
in SYSTEMPATH\Validation\Validation.php on line 320.
 1 SYSTEMPATH\Validation\Validation.php(320): CodeIgniter\Validation\Exceptions\ValidationException::forRuleNotFound('required,')
 2 SYSTEMPATH\Validation\Validation.php(170): CodeIgniter\Validation\Validation->processRules('name', 'name', null, [...], [...])
 3 SYSTEMPATH\Controller.php(140): CodeIgniter\Validation\Validation->run()
 4 APPPATH\Controllers\Welcome.php(25): CodeIgniter\Controller->validate([...])
 5 SYSTEMPATH\CodeIgniter.php(934): App\Controllers\Welcome->index()
 6 SYSTEMPATH\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Welcome))
 7 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 8 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
CRITICAL - 2023-02-09 12:19:20 --> Call to a member function listErrors() on null
in APPPATH\Views\newview.php on line 22.
 1 SYSTEMPATH\View\View.php(213): include()
 2 SYSTEMPATH\View\View.php(216): CodeIgniter\View\View->CodeIgniter\View\{closure}()
 3 SYSTEMPATH\Common.php(1177): CodeIgniter\View\View->render('newview', [], true)
 4 APPPATH\Controllers\Welcome.php(31): view('newview', [...])
 5 SYSTEMPATH\CodeIgniter.php(934): App\Controllers\Welcome->index()
 6 SYSTEMPATH\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Welcome))
 7 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 8 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
CRITICAL - 2023-02-09 12:32:59 --> Call to undefined method CodeIgniter\HTTP\IncomingRequest::getCurrentMethod()
in APPPATH\Controllers\Welcome.php on line 30.
 1 SYSTEMPATH\CodeIgniter.php(934): App\Controllers\Welcome->index()
 2 SYSTEMPATH\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Welcome))
 3 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 4 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
